language: rust
env:
  global:
  - PROJECT_NAME: subset-bam
  - RUST_BACKTRACE: full
matrix:
  fast_finish: true
  include:
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: WmRDPhN2x48rqNZSscMBRJ9ISiGII8Gxp3x0SEJW+EQUmsNMfJ23QxS9x59ZGNy9RMLF6u+LalyAsCo+Gn1XS4sj27imQ5keXWzHtsoENdThldoFybCkv3y/Gj5/zUWfUXFaNoMm8yiTHr0gZCnv5sRfgI0BaEfxBkLz7DRasfCw13UjncLwk56A20iD8SEFeGNggE8rj/TxLJuaHMldQdvZMnnV0WGo6KdFRz7tr3c381PO/ps0/L7NWgAOlrz0uaZ27KYycVLKUjmhkeV7gzm15VJDDnsAKhUAyqlJWpMAIVimU6mdi6XCJ1M/mpwQJiU9L8YzKcIKTTURuxVwH8NNqzwIitQcxgg/G182p2/yxdawEmgz+DKPgzZfuiBlp3xLu8P17aLdNSKoSn9ATvJPYIIjkJ+dgJ6rJTDCBbNtTTDTWEyK2ka8nmKmY3wE3ky6PCedRkxSuMs40x3cP2XQWIY5o7W4uWodXpINjHwJyYdqmmBN/z0K+k4DMrypf4A7XgSXzyRfRK3S0JpRZfmxnBMu8fGkJec5oTycJDKN7COGhbGdwDeMg4TjyHgJEr/xEXyXY+isN4McxKeFQ3qZcTL7MS/G0SlkkQ+Y97xYUNg5hXouXJIfuHWLGnysahSwfJm6/2oUvNk1ANB9NFqj+kT7CiifbwbiLAHvcOc=
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: 10XDev/subset-bam
    branch: master
    tags: true
    condition: "$TARGET = x86_64-apple-darwin"
