on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build and Upload Release 

env:
  CARGO_INCREMENTAL: 0

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u 10xbuild -p ${{secrets.GH_PAT}}
      - name: Make release build
        run: >
          docker run -v ${{github.workspace}}:/root
          -e GITHUB_SHA -e GITHUB_REF
          docker.pkg.github.com/10xdev/toolchain-scripts/toolchain:latest
          /bin/bash -lec '
          cargo build --release;
          target/release/subset-bam --help | grep -q subset-bam;
          readelf -V target/release/subset-bam;
          ';
          mkdir ${{runner.temp}}/artifacts;
          cp -a target/release/subset-bam ${{runner.temp}}/artifacts/subset-bam-linux
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: subset-bam
          path: ${{runner.temp}}/artifacts
  macos:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Make release build
        run: |
          cargo build --release
          target/release/subset-bam --help | grep -q subset-bam
          mkdir ${{runner.temp}}/artifacts
          cp -a target/release/subset-bam ${{runner.temp}}/artifacts/subset-bam-macos
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: subset-bam
          path: ${{runner.temp}}/artifacts

  setup-release:
    needs: [linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: subset-bam
          path: ${{runner.temp}}/artifacts

      - run: ls ${{runner.temp}}/artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Linux
        id: upload-linux-release 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{runner.temp}}/artifacts/subset-bam-linux
          asset_name: subset-bam_linux
          asset_content_type: application/octet-stream

      - name: Upload Mac
        id: upload-mac-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{runner.temp}}/artifacts/subset-bam-macos
          asset_name: subset-bam_macos
          asset_content_type: application/octet-stream
